Final refactoring registration test
timbortnik/EcoMap pull request #17
Opened 2017-04-07 16:26 UTC by nklymenok

Final refactoring of registration test

2017-04-07 16:40 UTC, DmyMi requested changes
Please delete "HomeUserPageLocator" from line 3, as you are not using it

2017-04-07 16:40 UTC, DmyMi approved these changes

2017-04-07 17:38 UTC, DmyMi requested changes

2017-04-07 17:38 UTC, DmyMi commented on page_object_ecomap/tests/TestRegistration.py
> +        self.user_page.is_logout_btn_present()
this method returns "true", you forgot assertTrue :) missed this at first glance

2017-04-07 17:45 UTC, timbortnik approved these changes

2017-04-07 21:03 UTC, DmyMi approved these changes

2017-04-07 21:06 UTC, merged

2017-04-12 16:03 UTC, nklymenok commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Check registration with valid data](https://trello.com/c/7KkdDnb1/15-2-check-registration-with-valid-data)