Anastasiia latysh
timbortnik/EcoMap pull request #7
Opened 2017-03-31 17:37 UTC by AnastasiiaLatysh

2017-04-01 08:18 UTC, timbortnik commented
How can it be executed?
Tried that:
EcoMap$ nosetests

----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK

2017-04-01 08:20 UTC, timbortnik requested changes
Need some way to run tests from command line

2017-04-03 10:40 UTC, nklymenok commented
For me, clear scheme to understand.
It would be convenient for me to have one file with locators (for each page create class with locators), read User`s info from file and use git ignore

2017-04-03 15:27 UTC, timbortnik approved these changes

2017-04-03 15:34 UTC, closed without merging