Anastasiia Bond
timbortnik/EcoMap pull request #8
Opened 2017-03-31 18:16 UTC by alianInGitHub

2017-04-01 07:57 UTC, timbortnik commented on TestEcoMap/.gitignore
> +.idea
Can we have an EOL here?

2017-04-01 08:03 UTC, timbortnik reviewed
TestEcoMap$ nosetests
.
----------------------------------------------------------------------
Ran 1 test in 8.859s

OK
(yey)

2017-04-01 08:05 UTC, timbortnik commented on TestEcoMap/TestBox/Test.py
> +
Shall we assert that login actually happened?

2017-04-01 08:07 UTC, timbortnik commented on TestEcoMap/TestBox/Test.py
> +     unittest.main()
This did not work for me
$ python TestBox/Test.py
Traceback (most recent call last):
  File "TestBox/Test.py", line 2, in <module>
    from pages.PageFactory import PageFactory
ImportError: No module named pages.PageFactory

Do we ever need to cal this out of unittest?

2017-04-01 08:12 UTC, timbortnik commented
Would be great to fix style issues
![image](https://cloud.githubusercontent.com/assets/2828549/24576861/1828f760-16cc-11e7-96e7-883347771474.png)

2017-04-01 08:14 UTC, timbortnik requested changes
Great PR, it actually works!
Would be nice to address minor issues.

2017-04-03 10:44 UTC, nklymenok commented
It would be better to read User`s info from the file.
For me not easy to understand this realisation, need more time  :)

2017-04-03 15:27 UTC, timbortnik approved these changes

2017-04-03 15:32 UTC, closed without merging